modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/sokcuri/naraechat/issues"
license="GNU Lesser General Public License v3.0"
[[mods]]
modId="aramchat"
version="1.0.0"
displayName="Aram Chat"
updateJSONURL="https://raw.githubusercontent.com/sokcuri/naraechat/master/data/update.json"
displayURL="https://github.com/sokcuri/naraechat"
authors="lklab"
description="아람챗은 마인크래프트 한글 입력을 도와줍니다. ported by LK-LAB fork from NaraeChat"

[[dependencies.naraechat]] #
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.naraechat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
